config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :categories

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy
'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :post_categories
  has_many :posts, :through => :post_categories
  belongs_to :topic

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :post_categories
  has_many :categories, :through => :post_categories

end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :categories
  has_many :posts

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: 4..30
  VALID_EMAIL_REGEX = /(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)/i

  validates :email,
            presence: true,
            length: 8..50,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You need to be logged in for this one."
      redirect_to posts_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:update, :edit, :destroy]
  def index
    @posts = Post.all

  end

  def show
    @post = Post.find(params[:id])

  end

  def new
    @topics = Topic.all
    @post = Post.new

  end

  def create
    @topics = Topic.all
    @post = Post.new(post_params)
    @post.user = User.find(session[:user_id]) if session[:user_id]

    if @post.save
      flash[:success] = "Post was made successfully!"
      redirect_to posts_path
    else
      render "new"
    end

  end

  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "You succesfully deleted the post."
    redirect_to posts_path
  end


  private


  def post_params
    params.require(:post).permit(:title, :description, :topic_id)
  end

  def require_same_user
    if current_user != @post.user
      flash[:danger] = "You can only change your own post"
      redirect_to posts_path

    end

  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "You have successfully logged in!"
      redirect_to user_path(@user)
    else
      flash[:danger] = "There's something wrong with your login information."
      render "new"

    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have succesfully logged out."
    redirect_to posts_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  end

  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created successfully!"
      redirect_to user_path(@user)
    else
      render 'users/new'
    end

  end

  def destroy
    @user = User.find(params[:id])
    if session[:user_id] == @user
      session[:user_id] = nil
    end
    if @user.destroy
      flash[:success] = "User has been deleted"
      redirect_to posts_path
    else
      flash[:danger] = "We couldn't find the user."
      render user_path(@user)
    end

  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_article.html.erb
<% @category.posts.each do |post| %>
  <div class="post">
    <div class="wrap-ut pull-left">
      <div class="userinfo pull-left">
        <div class="avatar">
          <%= image_tag "images/avatar.jpg" %>
        </div>

      </div>
      <div class="posttext pull-left">
        <%= link_to post.user.username, user_path(post.user) %>

        <h2><%= link_to post.title, post_path(post) %></a></h2>
        <%= post.description %>
        <hr>

        <p>Post created <%= time_ago_in_words post.created_at %> ago.</p>

      </div>
      <% if post.user == current_user %>
      <div class="clearfix" style="padding-left: 100px; padding-bottom: 20px;">
        <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", post_path(post), method: :delete,
                    data:{confirm: "Are you sure?"},
                    class: "btn btn-xs btn-danger" %>
      </div>
        <% end %>
    </div>
    <div class="postinfo pull-left">
      <div class="comments">
        <div class="commentbg">
          560
          <div class="mark"></div>
        </div>

      </div>
      <div class="views"><i class="fa fa-eye"></i> 1,568</div>
      <div class="time"><i class="fa fa-clock-o"></i> 24 min</div>
    </div>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/categories/_categories.html.erb
<h1 align="center">Categories</h1>

<% @categories.each do |category| %>
  <div class="post">
    <div class="wrap-ut pull-left">
      <div class="userinfo pull-left">


      </div>

        <h2 align="center" style="padding-top: 20px;"><%= link_to category.name, category_path(category) %></a></h2>


      <div class="clearfix" style="padding-left: 100px; padding-bottom: 20px;">

      </div>
    </div>

    <div class="clearfix"></div>
  </div>
<% end %>

app/views/categories/index.html.erb
<%= render "categories/categories" %>

app/views/categories/show.html.erb
<%= render 'article' %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

      <% flash.each do |name, msg| %>

        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %> 

        </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="headernav">
  <div class="container">
    <div class="row">
      <div class="col-lg-1 col-xs-3 col-sm-2 col-md-2 logo ">
        <%= link_to posts_path do %>
          <%= image_tag "images/logo.jpg" %>
          <% end %>
      </div>
      <div class="col-lg-3 col-xs-9 col-sm-5 col-md-3 selecttopic">
        <%= select_tag :topics, options_for_select(Topic.all.collect {
            |t|
           link_to t.name, ""})%>

      </div>
      <div class="col-lg-4 search hidden-xs hidden-sm col-md-3">
        <div class="wrap">
          <form action="#" method="post" class="form">
            <div class="pull-left txt"><input type="text" class="form-control" placeholder="Search Topics"></div>
            <div class="pull-right"><button class="btn btn-default" type="button"><i class="fa fa-search"></i></button></div>
            <div class="clearfix"></div>
          </form>
        </div>
      </div>
      <div class="col-lg-4 col-xs-12 col-sm-5 col-md-4 avt">
        <div class="stnt pull-left">
          <%= link_to "Start New Topic", new_post_path, class: "btn btn-primary" %>
          </form>
        </div>

        <% if logged_in? %>
          <div class="env pull-left"><%= link_to "Logout", logout_path %></div>
          <h5><%= link_to current_user.username, user_path(current_user) %></h5>
          <% else %>
          <div class="env pull-left"><%= link_to " Login", login_path %></div>
          <h5><%= link_to "Sign Up ", signup_path %> </h5>

      <%end%>

        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_pagination.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-xs-12">
      <div class="pull-left"><a href="#" class="prevnext"><i class="fa fa-angle-left"></i></a></div>
      <div class="pull-left">
        <ul class="paginationforum">
          <li class="hidden-xs"><a href="#">1</a></li>
          <li class="hidden-xs"><a href="#">2</a></li>
          <li class="hidden-xs"><a href="#">3</a></li>
          <li class="hidden-xs"><a href="#">4</a></li>
          <li><a href="#">5</a></li>
          <li><a href="#">6</a></li>
          <li><a href="#" class="active">7</a></li>
          <li><a href="#">8</a></li>
          <li class="hidden-xs"><a href="#">9</a></li>
          <li class="hidden-xs"><a href="#">10</a></li>
          <li class="hidden-xs hidden-md"><a href="#">11</a></li>
          <li class="hidden-xs hidden-md"><a href="#">12</a></li>
          <li class="hidden-xs hidden-sm hidden-md"><a href="#">13</a></li>
          <li><a href="#">1586</a></li>
        </ul>
      </div>
      <div class="pull-left"><a href="#" class="prevnext last"><i class="fa fa-angle-right"></i></a></div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/layouts/_pagination_top.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-xs-12 col-md-8">
      <div class="pull-left"><a href="#" class="prevnext"><i class="fa fa-angle-left"></i></a></div>
      <div class="pull-left">
        <ul class="paginationforum">
          <li class="hidden-xs"><a href="#">1</a></li>
          <li class="hidden-xs"><a href="#">2</a></li>
          <li class="hidden-xs"><a href="#">3</a></li>
          <li class="hidden-xs"><a href="#">4</a></li>
          <li><a href="#">5</a></li>
          <li><a href="#">6</a></li>
          <li><a href="#" class="active">7</a></li>
          <li><a href="#">8</a></li>
          <li class="hidden-xs"><a href="#">9</a></li>
          <li class="hidden-xs"><a href="#">10</a></li>
          <li class="hidden-xs hidden-md"><a href="#">11</a></li>
          <li class="hidden-xs hidden-md"><a href="#">12</a></li>
          <li class="hidden-xs hidden-sm hidden-md"><a href="#">13</a></li>
          <li><a href="#">1586</a></li>
        </ul>
      </div>
      <div class="pull-left"><a href="#" class="prevnext last"><i class="fa fa-angle-right"></i></a></div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
  <!-- -->
  <div class="sidebarblock">
    <h3>Categories</h3>
    <div class="divline"></div>
    <div class="blocktxt">
      <ul class="cats">
        <% Category.all.each do |cat|%>
        <li><a href=<%= category_path(cat) %>><%= cat.name %> <span class="badge pull-right"><%= cat.posts.count %></span></a></li>
        <%end%>

      </ul>
    </div>
  </div>

  <!-- -->
  <div class="sidebarblock">
    <h3>Topics</h3>
    <div class="divline"></div>
    <div class="blocktxt">
      <ul class="cats">
        <% Topic.all.each do |topic| %>

        <li><a href="#"><%=topic.name%><span class="badge pull-right"><%= topic.posts.count %></span></a></li>

          <%end%>
      </ul>
    </div>
  </div>

  <!-- -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChocolatGlace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <%= render 'layouts/navigation' %>

  <section class="content">
    <%= render 'layouts/messages' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-8">
          <%= yield %>
        </div>
        <div class="col-lg-4 col-md-4">
          <%= render 'layouts/sidebar' %>
        </div>
      </div>
    </div>
  </section>

  <%= render 'layouts/pagination' %>

  <%= debug(params) if Rails.env.development? %>

  </body>

</html>

app/views/posts/_article.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <div class="wrap-ut pull-left">
      <div class="userinfo pull-left">
        <div class="avatar">
          <%= image_tag "images/avatar.jpg" %>
          <div class="status green">&nbsp;</div>
        </div>

      </div>
      <div class="posttext pull-left">
        <h2><%= link_to post.title, post_path(post) %></a></h2>
        <%= post.description %>
        <hr>

        <p>Post created <%= time_ago_in_words post.created_at %> ago.</p>

      </div>
      <div class="clearfix" style="padding-left: 100px; padding-bottom: 20px;">
        <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", post_path(post), method: :delete,
                    data:{confirm: "Are you sure?"},
                    class: "btn btn-xs btn-danger" %>
      </div>
    </div>
    <div class="postinfo pull-left">
      <div class="comments">
        <div class="commentbg">
          560
          <div class="mark"></div>
        </div>

      </div>
      <div class="views"><i class="fa fa-eye"></i> 1,568</div>
      <div class="time"><i class="fa fa-clock-o"></i> 24 min</div>
    </div>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-8">



      <!-- POST -->
      <div class="post">
        <%= form_for(@post, :html => {class:"form newtopic", role: "form" }) do |field| %>

          <div class="topwrap">
            <div class="userinfo pull-left">
              <div class="avatar">
                <div class="status red">&nbsp;</div>
              </div>


            </div>
            <div class="posttext pull-left">

              <div>
                <%= field.text_field :title, class: "form-control", placeholder: "Enter post title" %>
              </div>

              <div class="row">
                <div class="col-lg-6 col-md-6">
                  <select name="category" id="category" class="form-control">
                    <option value="" disabled="disabled" selected="selected">Select Category</option>
                    <option value="op1">Option1</option>
                    <option value="op2">Option2</option>
                  </select>
                </div>
                <div class="col-lg-6 col-md-6">
                  <select name="subcategory" id="subcategory" class="form-control">
                    <option value="" disabled="disabled" selected="selected">Select Subcategory</option>
                    <option value="op1">Option1</option>
                    <option value="op2">Option2</option>
                  </select>
                </div>
              </div>

              <div>
                <%= field.text_area :description, class: "form-control", placeholder: "Type in the description"%>
              </div>
              <div class="row newtopcheckbox">
                <div class="col-lg-6 col-md-6">
                  <div><p>Who can see this?</p></div>
                  <div class="row">
                    <div class="col-lg-6 col-md-6">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox" id="everyone"> Everyone
                        </label>
                      </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox" id="friends"> Only Friends
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 col-md-6">


                </div>
              </div>


            </div>
            <div class="clearfix"></div>
          </div>
          <div class="postinfobot">


            <div class="pull-right postreply">
              <div class="pull-left smile"><a href="#"><i class="fa fa-smile-o"></i></a></div>
              <div class="pull-left"><%= field.submit class: "btn btn-primary"%>
              </div>
              <div class="clearfix"></div>
            </div>


            <div class="clearfix"></div>
          </div>
        <% end %>
      </div><!-- POST -->







    </div>

  </div>
</div>

app/views/posts/index.html.erb
        <!-- "<div class="container-fluid">

                        <div class="col-lg-8 col-xs-12 col-md-8">
                            <div class="pull-left"><a href="#" class="prevnext"><i class="fa fa-angle-left"></i></a></div>
                            <div class="pull-left">
                                <ul class="paginationforum">
                                    <li class="hidden-xs"><a href="#">1</a></li>
                                    <li class="hidden-xs"><a href="#">2</a></li>
                                    <li class="hidden-xs"><a href="#">3</a></li>
                                    <li class="hidden-xs"><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">6</a></li>
                                    <li><a href="#" class="active">7</a></li>
                                    <li><a href="#">8</a></li>
                                    <li class="hidden-xs"><a href="#">9</a></li>
                                    <li class="hidden-xs"><a href="#">10</a></li>
                                    <li class="hidden-xs hidden-md"><a href="#">11</a></li>
                                    <li class="hidden-xs hidden-md"><a href="#">12</a></li>
                                    <li class="hidden-xs hidden-sm hidden-md"><a href="#">13</a></li>
                                    <li><a href="#">1586</a></li>
                                </ul>
                            </div>
                            <div class="pull-left"><a href="#" class="prevnext last"><i class="fa fa-angle-right"></i></a></div>
                            <div class="clearfix"></div>
                        </div>
                    </div>

-->

<%= render "posts/article" %>

app/views/posts/new.html.erb
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">

                            <!-- POST -->
                            <div class="post">
                              <%= render 'shared/errors', obj: @post %>
                              <%= form_for(@post, :html => {class:"form newtopic", role: "form" }) do |field| %>

                                    <div class="topwrap">
                                        <div class="userinfo pull-left">
                                            <div class="avatar">
                                                <div class="status red">&nbsp;</div>
                                            </div>


                                        </div>
                                        <div class="posttext pull-left">

                                            <div>
                                              <%= field.text_field :title, class: "form-control", placeholder: "Enter post title" %>
                                            </div>

                                            <div class="row">
                                                <div class="col-lg-6 col-md-6">

                                                  <%= field.select :topic_id,
                                                                   Topic.all.collect {|p| [p.name, p.id]}, { include_blank: true } %>
                                                    </div>
                                                <div class="col-lg-6 col-md-6">
                                                    <select name="subcategory" id="subcategory" class="form-control">
                                                        <option value="" disabled="disabled" selected="selected">Select Subcategory</option>
                                                        <option value="op1">Option1</option>
                                                        <option value="op2">Option2</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div>
                                              <%= field.text_area :description, class: "form-control", placeholder: "Type in the description"%>
                                            </div>
                                            <div class="row newtopcheckbox">
                                                <div class="col-lg-6 col-md-6">
                                                    <div><p>Who can see this?</p></div>
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-6">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input type="checkbox" id="everyone"> Everyone
                                                                </label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-6">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input type="checkbox" id="friends"> Only Friends
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-6">


                                                </div>
                                            </div>


                                        </div>
                                        <div class="clearfix"></div>
                                    </div>                              
                                    <div class="postinfobot">


                                        <div class="pull-right postreply">
                                            <div class="pull-left smile"><a href="#"><i class="fa fa-smile-o"></i></a></div>
                                            <div class="pull-left"><%= field.submit class: "btn btn-primary"%>
                                              </div>
                                            <div class="clearfix"></div>
                                        </div>


                                        <div class="clearfix"></div>
                                    </div>
                                <% end %>
                            </div><!-- POST -->







                        </div>

                    </div>
                </div>

app/views/posts/show.html.erb
<div class="post">
  <div class="wrap-ut pull-left">
    <div class="userinfo pull-left">
      <div class="avatar">
        <%= image_tag "images/avatar.jpg" %>
      </div>

    </div>
    <div class="posttext pull-left">
      <%= link_to @post.user.username, user_path(@post.user) %>

      <h2><%= link_to @post.title, post_path(@post) %></a></h2>
      <%= @post.description %>
      <hr>

      <p>Post created <%= time_ago_in_words @post.created_at %> ago.</p>

    </div>
    <% if @post.user == current_user %>
    <div class="clearfix" style="padding-left: 100px; padding-bottom: 20px;">
      <%= link_to "Edit", edit_post_path(@post), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete", post_path(@post), method: :delete,
                  data:{confirm: "Are you sure?"},
                  class: "btn btn-xs btn-danger" %>
    </div>
      <% end %>
  </div>
  <div class="postinfo pull-left">
    <div class="comments">
      <div class="commentbg">
        560
        <div class="mark"></div>
      </div>

    </div>
    <div class="views"><i class="fa fa-eye"></i> 1,568</div>
    <div class="time"><i class="fa fa-clock-o"></i> 24 min</div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |msg| %>
     <% flash[:danger] =  msg %>
            <%end%>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>
<div class="post">
  <%= form_for @user, :html => {class: "form newtopic", role: "form"} do |field|%>
    <div class="postinfotop">
      <h2>Create New Account</h2>
    </div>

    <!-- acc section -->
    <div class="accsection">
      <div class="acccap">
        <div class="userinfo pull-left">&nbsp;</div>
        <div class="clearfix"></div>
      </div>
      <div class="topwrap">
        <div class="userinfo pull-left">
          <div class="avatar">
            <img src="" alt="" />
          </div>
          <div class="imgsize">60 x 60</div>
          <div>
            <button class="btn">Add</button>
          </div>
        </div>
        <div class="posttext pull-left">
          <div class="row">
            <div class="col-lg-12 col-md-12">
              <%= field.text_field :username, class: "form-control", placeholder: "Username" %>
            </div>

          </div>
          <div>
            <%= field.text_field :email, class: "form-control", placeholder: "Email"%>
          </div>
          <div class="row">
            <div class="col-lg-6 col-md-12">
              <%= field.password_field :password, class:"form-control", placeholder: "Password"%>
            </div>

          </div>

        </div>
        <div class="clearfix"></div>
      </div>
    </div><!-- acc section END -->



    <div class="postinfobot">

      <div class="pull-right postreply">
        <div class="pull-left">
          <%= field.submit class: "btn btn-primary" %>
        </div>
        <div class="clearfix"></div>
      </div>


      <div class="clearfix"></div>
    </div>
    </form>
  <% end %>
</div><!-- POST -->

app/views/users/_posts.html.erb
<% @user.posts.each do |post| %>
  <div class="post">
    <div class="wrap-ut pull-left">
      <div class="userinfo pull-left">
        <div class="avatar">
          <%= image_tag "images/avatar.jpg" %>
        </div>

      </div>
      <div class="posttext pull-left">
        <%= link_to post.user.username, user_path(post.user) %>

        <h2><%= link_to post.title, post_path(post) %></a></h2>
        <%= post.description %>
        <hr>

        <p>Post created <%= time_ago_in_words post.created_at %> ago.</p>

      </div>
      <div class="clearfix" style="padding-left: 100px; padding-bottom: 20px;">
        <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", post_path(post), method: :delete,
                    data:{confirm: "Are you sure?"},
                    class: "btn btn-xs btn-danger" %>
      </div>
    </div>
    <div class="postinfo pull-left">
      <div class="comments">
        <div class="commentbg">
          560
          <div class="mark"></div>
        </div>

      </div>
      <div class="views"><i class="fa fa-eye"></i> 1,568</div>
      <div class="time"><i class="fa fa-clock-o"></i> 24 min</div>
    </div>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render "users/form" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= render "users/form" %>

app/views/users/show.html.erb
<div class="post">
<div class="custom">
<h1 align="center"><%= @user.username %></h1>
  <h2 align="center">  <%= pluralize @user.posts.count, "post" %></h2>
  <% if current_user == @user %>
  <h3 align="center"><%= link_to "Edit Your Information", edit_user_path(@user) %></h3>
  <h3 align="center"><%= link_to "Delete This User", user_path(@user), method: :delete %></h3>
    <% end %>

</div>

</div>
<%= render "users/posts" %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>